### ISSUE TITLE
Poziome linie na wykresach w ggplot2

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/PISAoccupations#10]
W theme powinno się je dać ustawić, gdyby lewa oś była gęstsza,. np. co 20 pkt to łatwo byłoby precyzyjnie odczytać wartości z wykresu

**Comment by mstaniak** [comment]
Zdaje się, że jest jakiś konflikt między gridlines a theme_tufte, stąd tymczasowy powróß do theme_bw
