### ISSUE TITLE
Ustawić domyślne wielkości wykresów dla ggvis tak by zajmowały całe dostępne miejsce

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/PISAoccupations#17]

**Comment by mstaniak** [comment]
Ostatni wykres działa.
Wykresy, które żyją na sąsiednich panelach, ciągle są problemem. 
W ostateczności może verticalLayout zamiast splitLayout będzie dobrm pomysłem.

**Comment by mstaniak** [comment]
Wygląda na to, żę już działa, ale trzeba będzie jeszcze potestować.

**Comment by mstaniak** [comment]
Zdaje się, że pojawił się problem z drugim panelem.

**Comment by mstaniak** [comment]
Śmieszne zachowanie ggvisa:
- po ustawieniu rozmiarów w panelu z dwoma wykresami obok siebie jeden wykres wyświetlał się pusty, dopóki nie zmieniło się kraju,
- po dodaniu opisów do wykresów wykres z ostatniego panelu zaczał się wydłużać w nieskończoność (trzeba było mu dodać verticalLayout), te dwa wykresy obok siebie nie sprawiały takich problemów.
