### ISSUE TITLE
Miniaturki wykresów

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/PISAoccupations#29]
Dla każdego z wykresów z zakłądek 1-4 zrobic screenshot z miniaturką wykresu o szerokości do 500px i wysokości 350px.
Umieścić je w extdata/www i podlinkować w miejsce [TODO] na stronach homeLeft, homeRight

**Comment by mstaniak** [comment]
Muszą poczekać na wykończenie wykresów, w tym rozwiązanie problemów z kolorami i rozmiarami.
