### ISSUE TITLE
Historie

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/PISAoccupations#30]
Najbardziej podoba mi się zakładka 'Trends in Education'
Poniżej kilka historii, najbardziej ciekawa jest dla UK, w której jest wielki spadek dla grupy 2 a niewielki dla 9. 

<img width="1409" alt="screen shot 2016-08-03 at 00 29 03" src="https://cloud.githubusercontent.com/assets/4624318/17347635/72b46bf2-5911-11e6-9589-b340419fc033.png">
<img width="1131" alt="screen shot 2016-08-03 at 00 28 23" src="https://cloud.githubusercontent.com/assets/4624318/17347637/72b7c356-5911-11e6-9851-a88ce4f93c46.png">
<img width="1419" alt="screen shot 2016-08-03 at 00 27 48" src="https://cloud.githubusercontent.com/assets/4624318/17347636/72b4a9e6-5911-11e6-9de3-4874ff084321.png">

**Comment by pbiecek** [comment]
Tak jest dla wszystkich trzech przedmiotów, i to jest historia

**Comment by mstaniak** [comment]
Dwie ciekawe historie:
- Japonia 2012: całkiem inna struktura niż w pozostałych krajach. 
- Meksyk na przestrzeni lat: zmniejszenie nierówności poprzez równoczesne obniżenie wyników wyższych kategorii i duże zwiększenie wyników najniższych kategorii.
