### ISSUE TITLE
Poprawienie mojej nazwy użytkownika w commitach.

### ISSUE THREAD

**Issue by mstaniak** [mi2-warsaw/PISAoccupations#37]
Jeśli to nie problem, odpalę skrypt z tej instrukcji:
https://help.github.com/articles/changing-author-info/
bo robiłem commity z ustawieniami ze starego konta.

**Comment by pbiecek** [comment]
jasne, właśnie dziwiło mnie to, że comity nie są podlinkowane do Twojego konta.
