### ISSUE TITLE
Wykresy interaktywne

### ISSUE THREAD

**Issue by mstaniak** [mi2-warsaw/PISAoccupations#38]
Ten pakiet:

https://www.r-bloggers.com/make-ggplot-graphics2-interactive-with-ggiraph/

daje nadzieję na jednolity wygląd wykresów z zachowaniem tooltipów. 
Sprawdzę szczegóły w przyszłym tygodniu, gdy już rozwiąże się sprawa projektu, o którym pisałem.

**Comment by pbiecek** [comment]
Pakiet wygląda bardzo ciekawie

**Comment by mstaniak** [comment]
Zrobione. Na później zostały detale, tj. rozmiary, w szczególności wykresy dla dwóch krajów, który teraz jest zbyt wąski.
