### ISSUE TITLE
Przyśpieszenie obliczeń

### ISSUE THREAD

**Issue by mstaniak** [mi2-warsaw/PISAoccupations#40]
Być może użycie Rcpp pomoże, być może nie warto się tym zajmować.

**Comment by pbiecek** [comment]
Myślę że nie warto, nie ma tutaj funkcji które w naturalny sposób dałoby się przepisać na Rcpp,
pozostałe można ale nie spodziewałbym się dużej zmiany.

Raczej użyłbym profilera, zobacz tu: https://support.rstudio.com/hc/en-us/articles/218221837-Profiling-with-RStudio
aby sprawdzić które fragmenty kodu sa wąskim gardłem

**Comment by mstaniak** [comment]
Profilowałem [trochę] kod jeszcze w Warszawie, problem był w oczywistym miejscu: kiedy wiele razy trzeba obliczyć wariancję. 
Widzę jedno miejsce, w którym można by użyć Rcpp: zastąpić lapply pętlą c++. 
W społeczności zdania co do tego, czy lapply jest przyśpieszeniem pętli napisanym w C, czy prostym wrapperem wokół for są podzielone, więc nie wiem, czy to coś zmieni. [Aktualnie wierzę w to drugie, ale chętnie bym się dowiedział, jak naprawdę jest]. Zajmę się tym tylko, jeśli starczy mi czasu po zrobieniu ważniejszych rzeczy, tj uporządkowaniu kodu i przygotowaniu wszystkiego do dodania nowych danych.
