### ISSUE TITLE
Interfejs aplikacji

### ISSUE THREAD

**Issue by mstaniak** [mi2-warsaw/PISAoccupations#41]
Można by go uprościć na podobieństwo tego, co zrobiłem tutaj:

https://comicbooktv.shinyapps.io/ratingsApp/

W zasadzie jedyny problem jest taki, że nasza strona główna jest bardzo duża, a w takiej sytuacji byłoby na nią mniej miejsca.

Pozwoliłoby to też zmniejszyć kod, obsługa byłab może trochę wygodniejsza.

**Comment by pbiecek** [comment]
Warto spróbować, choć niekoniecznie robiąc ciemne tło
Mam też wrażenie, że obecne menu jest dosyć proste, ale jeżeli można je uprości to warto

**Comment by mstaniak** [comment]
Jasne, chodziło mi o tę sprawę: jeden boczny panel zamiast czterech, zawsze widoczny. Jakieś motywy z ggthemes czy bootstrapu można pooglądać, ale na pewno jasne. Coś popróbuję i pokażę.
